<?php
/**
 * Contao 
 * English translation file 
 * 
 * copyright  Tim Gatzky 2015
 * author     Thomas Kettner <thomas.kettner@e-blick.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Plugin
 */
$GLOBALS['TL_LANG']['PCT_CUSTOMELEMENTS']['PLUGINS']['notelist'] = array('Notelist','This Plugin adds a notelist attribute and notelist filter to the CustomCatalog Plugin. Notelists can be sent via email by using a form field type "Notelist, CustomElements" in the form generator.');

/**
 * Attribute
 */
$GLOBALS['TL_LANG']['PCT_CUSTOMELEMENTS']['ATTRIBUTES']['notelist'] = array('Notelist','adds a notelist-Widget.');

/**
 * Filter
 */
$GLOBALS['TL_LANG']['PCT_CUSTOMELEMENTS']['FILTERS']['notelist'] = array('Notelist Items','filters list by notelist items');


/**
 * Frontend texts
 */
$GLOBALS['TL_LANG']['customelements_notelist']['submitLabel'] 			= 'Add to watchlist';
$GLOBALS['TL_LANG']['customelements_notelist']['amountLabel'] 			= 'Amount';
$GLOBALS['TL_LANG']['customelements_notelist']['removeLabel'] 			= 'Remove';
$GLOBALS['TL_LANG']['customelements_notelist']['updateLabel'] 			= 'Refresh';
$GLOBALS['TL_LANG']['customelements_notelist']['emptyLabel'] 			= '-';
$GLOBALS['TL_LANG']['customelements_notelist']['emptyInfo'] 			= 'Your watchlist is empty.';
$GLOBALS['TL_LANG']['customelements_notelist']['pleaseSelect'] 			= 'Please select';
$GLOBALS['TL_LANG']['customelements_notelist']['itemAdded'] 			= 'The item has been added to the watchlist.';
$GLOBALS['TL_LANG']['customelements_notelist']['itemUpdated'] 			= 'The item has been updated.';
$GLOBALS['TL_LANG']['customelements_notelist']['blankOption'] 			= '-';
