<?php
/**
 * Contao 
 * English translation file 
 * 
 * copyright  Tim Gatzky 2015
 * author     Thomas Kettner <thomas.kettner@e-blick.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['MOD']['pct_customelements_plugin_note'] 		= 'CustomElements/CustomCatalog Notelist Plugin';