<?php
/**
 * Contao 
 * English translation file 
 * 
 * copyright  Tim Gatzky 2015
 * author     Thomas Kettner <thomas.kettner@e-blick.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */



/**
 * Form fields
 */
$GLOBALS['TL_LANG']['FFL']['customelements_notelist']   	 				= array('Notelist, CustomElements', 'Send a Notelist via email');

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_form_field']['template_legend']  					= 'Template Settings';
$GLOBALS['TL_LANG']['tl_form_field']['settings_legend']  					= 'Configuration';

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_form_field']['customelements_notelist_formTpl']		= array('Frontend template','Here you can select a frontend template.');
$GLOBALS['TL_LANG']['tl_form_field']['customelements_notelist_mailTpl']		= array('Email template','Select an email template.');
$GLOBALS['TL_LANG']['tl_form_field']['customelements_notelist_source']		= array('Select source','Select the source of the notelist.');
$GLOBALS['TL_LANG']['tl_form_field']['customelements_notelist_visibles']	= array('Visible Fields','Select fields that will be visible.');