<?php
/**
 * Contao 
 * English translation file 
 * 
 * copyright  Tim Gatzky 2015
 * author     Thomas Kettner <thomas.kettner@e-blick.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */


/**
 * Type
 */
$GLOBALS['TL_LANG']['tl_metamodel_attribute']['typeOptions']['notelist']    = 'Notelist';

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['allowNotelistVariants'] 		= array('Allow variants','Click if the notelist will support variants.');
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['notelistVariants'] 			= array('Variants','Select all fields from which variants can be created and added to the notelist.');