<?php
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2015
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Plugin
 */
$GLOBALS['TL_LANG']['PCT_CUSTOMELEMENTS']['PLUGINS']['notelist'] = array('Merkliste','Dieses Plugin stellt für das CustomCatalog Plugin eine Merkliste-Attribute und Filter bereit. Merklisten können mit Hilfe eines Merkliste-Einträge-Formularfeld über den Formulargenerator per Mail verschickt werden.');

/**
 * Attribute
 */
$GLOBALS['TL_LANG']['PCT_CUSTOMELEMENTS']['ATTRIBUTES']['notelist'] = array('Merkliste','Fügt das Merkliste-Widget hinzu.');

/**
 * Filter
 */
$GLOBALS['TL_LANG']['PCT_CUSTOMELEMENTS']['FILTERS']['notelist'] = array('Merkliste-Einträge','Filtert die Liste nach Einträgen, die in der Merkliste liegen');


/**
 * Frontend texts
 */
$GLOBALS['TL_LANG']['customelements_notelist']['submitLabel'] 			= 'Auf Merkliste';
$GLOBALS['TL_LANG']['customelements_notelist']['amountLabel'] 			= 'Menge';
$GLOBALS['TL_LANG']['customelements_notelist']['removeLabel'] 			= 'Entfernen';
$GLOBALS['TL_LANG']['customelements_notelist']['updateLabel'] 			= 'Aktualisieren';
$GLOBALS['TL_LANG']['customelements_notelist']['emptyLabel'] 			= '-';
$GLOBALS['TL_LANG']['customelements_notelist']['emptyInfo'] 			= 'Ihre Merkliste ist leer.';
$GLOBALS['TL_LANG']['customelements_notelist']['pleaseSelect'] 			= 'Bitte wählen Sie';
$GLOBALS['TL_LANG']['customelements_notelist']['itemAdded'] 			= 'Der Eintrag wurde auf die Merkliste gelegt.';
$GLOBALS['TL_LANG']['customelements_notelist']['itemUpdated'] 			= 'Der Eintrag wurde aktualisiert.';
$GLOBALS['TL_LANG']['customelements_notelist']['blankOption'] 			= '-';
