<?php
	
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2015
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */


/**
 * Form fields
 */
$GLOBALS['TL_LANG']['FFL']['customelements_notelist']   	 				= array('Merkliste, CustomElements', 'Verschicken Sie eine Merkliste per Mail');

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_form_field']['template_legend']  					= 'Template-Einstellungen';
$GLOBALS['TL_LANG']['tl_form_field']['settings_legend']  					= 'Einstellungen';

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_form_field']['customelements_notelist_formTpl']		= array('Ausgabe-Template','Wählen Sie hier das Ausgabe-Template.');
$GLOBALS['TL_LANG']['tl_form_field']['customelements_notelist_mailTpl']		= array('Mail-Template','Wählen Sie hier das Mail-Template.');
$GLOBALS['TL_LANG']['tl_form_field']['customelements_notelist_source']		= array('Quelle auswählen','Wählen Sie hier die Quelle der Merkliste aus.');
$GLOBALS['TL_LANG']['tl_form_field']['customelements_notelist_visibles']	= array('Sichtbare Felder','Wählen Sie hier die sichtbaren Felder aus.');