<?php
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2013 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Type
 */
$GLOBALS['TL_LANG']['tl_metamodel_attribute']['typeOptions']['notelist']    = 'Merkliste';

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['allowNotelistVariants'] 		= array('Varianten erlauben','Wählen Sie hier, wenn die Merkliste Varianten unterstützen soll.');
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['notelistVariants'] 			= array('Varianten','Wählen Sie die Felder, aus denen Varianten in die Merkliste gelegt werden können.');